import { Button, Modal } from "@mui/material";
import React from "react";

export function CreditModal() {
  const [open, setOpen] = React.useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  return (
    <>
      <Button
        style={{
          textDecoration: "none",
          marginTop: "10px",
          color: "white",
          borderBottom: "4px solid #ccc",
        }}
        onClick={handleOpen}
      >
        {" See Credits "}
      </Button>
      <Modal
        open={open}
        onClose={handleClose}
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          margin: "5%",
        }}
        componentsProps={{
          backdrop: {
            style: { backgroundColor: "#111", opacity: "0.9" },
          },
        }}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
      >
        <div
          style={{
            backgroundColor: "white",
            position: "relative",
            display: "flex",
            flexDirection: "column",
            padding: "0 5% 0 5%",
            border: "2px solid #000",
            borderRadius: "10px",
            textAlign: "center",
          }}
        >
          <h5
            style={{
              borderBottom: "2px solid #000",
              paddingTop: "10px",
              paddingBottom: "10px",
            }}
          >
            WELCOME TO QUIZZYTALES
          </h5>
          <h6>ABOUT</h6>
          <span> v1.0</span>
          <span>
            Our website harnesses images to craft interactive stories and
            quizzes.
          </span>
          <span>
            Dive into visual narratives and test your knowledge with our
            AI-driven content.
          </span>
          <br />
          <h6>API USAGE</h6>
          <span>
            Image Classification : &nbsp;
            <a href="https://cloud.google.com/vision/" target="_blank">
              Google Vision AI
            </a>
          </span>
          <span>
            Translation : &nbsp;
            <a href="https://cloud.google.com/translate/" target="_blank">
              Google Translation AI
            </a>
          </span>
          <span>
            Story&Quiz Generation : &nbsp;
            <a href="https://openai.com/" target="_blank">
              OpenAI
            </a>
          </span>
          <br />
          <h6>CONTACT</h6>
          <span>
            If you enjoy this, you can kudos the&nbsp;
            <a href="https://github.com/hikariakio/quizzytales" target="_blank">
              repo
            </a>
            .
          </span>
          <span>
            Please also visit my&nbsp;
            <a href="http://yginnovatory.com" target="_blank">
              homepage
            </a>
            &nbsp;to see other awesome projects.
          </span>
          <br />
          <h6>DISCLAIMER</h6>
          <span>
            All content on QuizzyTales, including stories and quizzes, is
            generated by AI.
          </span>
          <span>
            Any resemblance to real events or individuals is coincidental.
          </span>
          <span>
            Quizzes may not always be accurate. Use at your own discretion.
          </span>
          <br />
          <br />
          <span> Developed by Ye Gaung</span>
          <span> Built with React.js</span>
          <br />
        </div>
      </Modal>
    </>
  );
}
