service: quizzytales

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  timeout: 30
  memorySize: 512

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
  dotenv:
    path: .env
    logging: true
